default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5)%>
  host: <%= ENV.fetch('RAILS_DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('RAILS_DATABASE_PORT', 3306) %>
  database: <%= ENV.fetch('RAILS_DATABASE', 'rails')%>
  username: <%= ENV.fetch('RAILS_DATABASE_USER', 'root') %>
  password: <%= ENV.fetch('RAILS_DATABASE_PASSWORD', '') %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch('RAILS_DATABASE_TEST', 'test')%>

production:
  <<: *default
